### ISSUE TITLE
Request: Add to Stackage

### ISSUE THREAD

**Issue by psibi** [hiratara/hs-random-string#12]
Would the author of the package be interested to add this to Stackage ?

Currently, the package `fakedata` depends on it and it's on the latest night build because of this. More details here: https://github.com/commercialhaskell/stackage/issues/5412

I can volunteer to add/maintain this in Stackage in case the author doesn't want to do it. But it's best if the author does that so as to do update necessary version constraints and release a package when it's needed (based on lts, nightly changes)

**Comment by psibi** [comment]
@hiratara Any updates on this ?

**Comment by hiratara** [comment]
@psibi  Sorry for the late reply.

I can do some maintenance to put `string-random` in Stackage. However, I don't know what exactly to do. What do I need to do? 

If you can put it in Stackage on your own, you can do that freely :)

**Comment by psibi** [comment]
@hiratara These are the steps: https://github.com/commercialhaskell/stackage#add-your-package

Let me know if you have any questions.

> If you can put it in Stackage on your own, you can do that freely :)

I can put it under my name, but I would prefer if it's under the original author instead. :-)

**Comment by hiratara** [comment]
@psibi I've just sent a PR https://github.com/commercialhaskell/stackage/pull/5457 .

**Comment by psibi** [comment]
Thanks @hiratara !

**Comment by psibi** [comment]
Closing this issue since the package is in Stackage now. Thanks for including it!
