### ISSUE TITLE
string-random-0.1.3.0 testsuite failing to build

### ISSUE THREAD

**Issue by juhp** [hiratara/hs-random-string#16]
For Stackage Nightly:

```
    Building test suite 'string-random-quickcheck' for string-random-0.1.3.0..
    [1 of 2] Compiling Main
    
    /var/stackage/work/unpack-dir/unpacked/string-random-0.1.3.0-31e80448992dc8642295172aee17de0179ff037c15b4eee4b4050a925430c7bf/te
st/string-random-quickcheck.hs:15:40: error:
        • No instance for (random-1.1:System.Random.RandomGen
                             splitmix-0.1.0.3:System.Random.SplitMix.SMGen)
            arising from a use of ‘StringRandom.stringRandom’
        • In the expression: StringRandom.stringRandom g regregexp
          In the second argument of ‘($)’, namely
            ‘\ (QC.QCGen g) _ -> StringRandom.stringRandom g regregexp’
          In the expression:
            QC.MkGen
              $ \ (QC.QCGen g) _ -> StringRandom.stringRandom g regregexp
       |
    15 | regexp = QC.MkGen $ \(QC.QCGen g) _ -> StringRandom.stringRandom g regregexp
       |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by hiratara** [comment]
It seems that `SMGen` does not implement `RandomGen` in `splitmix-0.1` or later.

http://hackage.haskell.org/package/splitmix-0.0.5/docs/System-Random-SplitMix.html#t:SMGen
http://hackage.haskell.org/package/splitmix-0.1/docs/System-Random-SplitMix.html#t:SMGen

**Comment by hiratara** [comment]
`random-1.2.0` has the instance `RandomGen SMGen` , so we should use that version instead of `random-1.1` . Actually, I passed all the tests with `random-1.2.0` .

https://hackage.haskell.org/package/random-1.2.0/docs/System-Random.html#t:RandomGen

It seems that https://www.stackage.org/nightly-2021-01-03 still uses `random-1.1` .

Related issues: https://github.com/haskellari/splitmix/issues/34

**Comment by hiratara** [comment]
Other issues:
https://github.com/nick8325/quickcheck/issues/300
https://github.com/nick8325/quickcheck/issues/302

**Comment by hiratara** [comment]
I've released https://hackage.haskell.org/package/string-random-0.1.4.0 .

Thank you for your report 😃
